package password

// englishWords contains lowercase English words written with plain ASCII only.
var englishWords = []string{
	"ability", "able", "aboard", "absent", "absorb", "access", "account", "acre",
	"action", "actor", "address", "adult", "advice", "affair", "after", "agency",
	"agent", "agenda", "ahead", "airport", "alarm", "album", "alert", "alley",
	"almost", "alpha", "amber", "amount", "angle", "animal", "answer", "apple",
	"apron", "april", "archive", "area", "arena", "artist", "aspect", "atlas",
	"audio", "august", "autumn", "avenue", "award", "baker", "balance", "banana",
	"banner", "barrel", "basic", "basket", "beacon", "beauty", "bedroom", "belief",
	"bench", "berry", "beyond", "bicycle", "binder", "biscuit", "blanket", "blossom",
	"border", "bottle", "branch", "bridge", "bright", "bronze", "brother", "budget",
	"building", "button", "cabin", "cable", "cactus", "camera", "candle", "canvas",
	"carbon", "carpet", "castle", "casual", "cedar", "center", "cereal", "chair",
	"chance", "change", "channel", "cherry", "circle", "citizen", "city", "claim",
	"class", "clean", "clever", "client", "climate", "clock", "closet", "cloud",
	"coffee", "collar", "colony", "color", "column", "comet", "common", "company",
	"corner", "cotton", "course", "cousin", "craft", "credit", "creek", "crystal",
	"culture", "current", "custom", "daily", "danger", "daughter", "daylight", "decade",
	"decent", "detail", "device", "dinner", "direct", "distant", "doctor", "domain",
	"dragon", "drawer", "dream", "dress", "driver", "during", "eagle", "early",
	"earth", "east", "echo", "editor", "effect", "effort", "elder", "element",
	"elevator", "engine", "entry", "equal", "estate", "evening", "event", "exact",
	"example", "fabric", "factor", "family", "famous", "farmer", "feather", "feature",
	"fence", "festival", "field", "figure", "filter", "final", "finger", "finish",
	"forest", "formal", "fortune", "forward", "fossil", "fountain", "frame", "freedom",
	"friend", "frost", "garden", "gather", "gentle", "giant", "ginger", "glass",
	"global", "golden", "grain", "grant", "grape", "gravity", "green", "harbor",
	"harmony", "harvest", "health", "heart", "helmet", "hidden", "history", "honest",
	"honey", "hotel", "humble", "idea", "image", "impact", "income", "island",
	"jacket", "journey", "jungle", "junior", "kettle", "kitchen", "ladder", "language",
	"lantern", "laptop", "later", "lawyer", "leader", "legacy", "lesson", "letter",
	"library", "light", "limit", "linen", "little", "local", "logic", "loyal",
	"machine", "magic", "market", "master", "meadow", "melody", "memory", "metal",
	"middle", "minute", "mirror", "mobile", "modern", "moment", "monday", "mountain",
	"museum", "music", "native", "nature", "nearby", "network", "neutral", "noble",
	"north", "notebook", "number", "object", "ocean", "office", "olive", "orange",
	"orbit", "order", "origin", "paper", "parent", "partner", "party", "pattern",
	"pebble", "pencil", "people", "pepper", "period", "person", "photo", "picnic",
	"planet", "plastic", "player", "pocket", "poetry", "polish", "popular", "prairie",
	"present", "pretty", "private", "problem", "public", "purple", "puzzle", "quality",
	"quarter", "question", "quick", "radio", "random", "reader", "reason", "record",
	"region", "report", "rescue", "result", "ribbon", "river", "rocket", "route",
	"sample", "school", "season", "second", "secret", "sector", "service", "shadow",
	"shelter", "signal", "silver", "simple", "sister", "skill", "smooth", "social",
	"solar", "solid", "source", "special", "spirit", "spring", "square", "stable",
	"station", "stone", "storage", "story", "stream", "street", "strong", "student",
	"summer", "supply", "system", "table", "talent", "teacher", "temple", "theory",
	"ticket", "timber", "title", "today", "tomato", "topic", "tower", "travel",
	"treaty", "tripod", "tunnel", "useful", "valley", "value", "velvet", "vendor",
	"version", "vessel", "video", "village", "vision", "visitor", "volume", "wallet",
	"window", "winter", "wisdom", "wonder", "yellow", "youth",
}
